context:
  version: "0.15.0"

package:
  name: tea
  version: ${{ version }}

source:
  - url: https://gitea.com/gitea/tea/archive/v${{ version }}.tar.gz
    sha256: ca8a6b39116617dac2bb46b53cd4021daea6a7ae6a8106fa6ef359c76b54118a
    target_directory: src
  - url: https://raw.githubusercontent.com/alecthomas/chroma/refs/heads/master/COPYING
    sha256: 13654b052f885cb3fa47d7343e13975d9c8a64c3bcd84993c35d5eb01f22b23f
    target_directory: alecthomas-chroma
    file_name: COPYING
  - if: win
    then:
      url: https://github.com/mattn/go-localereader/raw/master/LICENSE
      sha256: dceede03550621e65ec7b79fcba87cf6dbb9d31132a8ae71a8fe8ceec0af7da3
      target_directory: go-localereader-license
      file_name: LICENSE

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses --ignore github.com/go-authgate/sdk-go --ignore github.com/alecthomas/chroma ${{ "--ignore github.com/mattn/go-localereader" if win }}
    - if: win
      then:
        - mkdir ..\library_licenses\github.com\mattn\go-localereader
        - copy ..\go-localereader-license\LICENSE ..\library_licenses\github.com\mattn\go-localereader\LICENSE
    - if: unix
      then:
        - go build -v -o $PREFIX/bin/tea -ldflags="-s -w"
        - mkdir -p $PREFIX/share/zsh/site-functions $PREFIX/share/bash-completion/completions $PREFIX/share/fish/vendor_completions.d
        - $PREFIX/bin/tea completion zsh > $PREFIX/share/zsh/site-functions/_tea
        - $PREFIX/bin/tea completion bash > $PREFIX/share/bash-completion/completions/tea
        - $PREFIX/bin/tea completion fish > $PREFIX/share/fish/vendor_completions.d/tea.fish
      else: go build -v -o %LIBRARY_BIN%\tea.exe -ldflags="-s"
requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - tea --version
  - package_contents:
      bin:
        - tea
      files:
        - if: unix
          then:
            - share/bash-completion/completions/tea
            - share/fish/vendor_completions.d/tea.fish
            - share/zsh/site-functions/_tea
      strict: true

about:
  homepage: https://gitea.com/gitea/tea
  summary: A command line tool to interact with Gitea servers
  description: |
    tea is the official CLI for Gitea. It can be used to manage and
    interact with Gitea servers from the command line.
  license: MIT
  license_file:
    - src/LICENSE
    - library_licenses/
    - LICENSE-go-authgate
    - alecthomas-chroma/COPYING
  documentation: https://gitea.com/gitea/tea
  repository: https://gitea.com/gitea/tea

extra:
  recipe-maintainers:
    - pavelzw
